name: Build stable version

on:
  push:
    branches:
      - main
      - 'push-action/**'
    paths:
      - '**'
      - '!chart/**'
      - '!pom.xml'
      - '!README.md'

jobs:
  compile:
    runs-on: ubuntu-20.04
    outputs:
      new_version: ${{ steps.bump_semver.outputs.new_version }}
    strategy:
      matrix:
        java: [ 8 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Check PR labels action step
        id: check_pr_labels_major
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["major"]'

      - name: Check PR labels action step
        id: check_pr_labels_minor
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["minor"]'

      - name: Check PR labels action step
        id: check_pr_labels_patch
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["patch"]'

      - name: Select proper label
        run: |
          if [[ "${{ steps.check_pr_labels_major.outputs.result }}" = true ]]; then
            echo "CORRECT_LABEL=$(echo "major")" >> $GITHUB_ENV
          elif [[ "${{ steps.check_pr_labels_minor.outputs.result }}" = true ]]; then
            echo "CORRECT_LABEL=$(echo "minor")" >> $GITHUB_ENV
          elif [[ "${{ steps.check_pr_labels_patch.outputs.result }}" = true ]]; then
            echo "CORRECT_LABEL=$(echo "patch")" >> $GITHUB_ENV
          else
            echo "You need to specify correct label for your PR (major, minor or patch)"
            exit 1
          fi

      - name: Get current release version
        id: release_version
        run: |
          echo "::set-output name=release::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      - name: Calculate new version
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump_semver
        with:
          current_version: ${{ steps.release_version.outputs.release }}
          level: ${{ env.CORRECT_LABEL }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: ${{ matrix.java }}

      - name: Compile the Project
        run: |
          mvn versions:set -DnewVersion=${{ steps.bump_semver.outputs.new_version }} -DprocessAllModules
          mvn -B compile

  build:
    runs-on: ubuntu-20.04
    needs: compile
    name: Build the Maven Project
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN_DENIS }}
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: behoof4mind
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          java-package: jdk
      - name: Change version
        run: |
          mvn versions:set -DnewVersion=${{ needs.compile.outputs.new_version }}
          mvn versions:commit -DprocessAllModules
          git add pom.xml
          git commit -m "[Auto-Update] Version updated"
          git push
      - name: Commit and push updated pom.xml
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.TOKEN_DENIS }}
          branch: main
      - name: Build and test project
        run: mvn -B deploy -DnewVersion=${{ needs.compile.outputs.new_version }} -DprocessAllModules
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.compile.outputs.new_version }}
          files: |
            target/*.jar
